# Generated by Django 4.2.4 on 2023-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses_taught',
        ),
        migrations.AddField(
            model_name='professor',
            name='courses_taught',
            field=models.ManyToManyField(to='timetable.course'),
        ),
    ]
